#!/usr/bin/python

TYPE_STATUS = \
[[ (), 'incomplete', 'every relation should have a type tag'],
 [ ('Bridge',), 'typo', 'use type=bridge'],
 [ ('Building',), 'typo', 'use type=building'],
 [ ('Route',), 'typo', 'use type=route'],
 [ ('boundary','administrative'), 'established', 'consider using type=multipolygon'],
 [ ('bridge',), 'proposed', ''],
 [ ('bridge','yes'), 'redundant', 'bridge=yes is redundant'],
 [ ('building',), 'proposed', ''],
 [ ('building','yes'), 'redundant', 'building=yes is redundant'],
 [ ('circuit',), 'proposed', ''],
 [ ('country',), 'proposed', ''],
 [ ('collection', 'river',), 'deprecated', 'use type=waterway, waterway=river'],
 [ ('collection', 'stream',), 'deprecated', 'use type=waterway, waterway=stream'],
 [ ('collection', 'waterway',), 'deprecated', 'use type=waterway, waterway=*'],
 [ ('collection', 'waterway', 'river'), 'deprecated', 'use type=waterway, waterway=river'],
 [ ('collection', 'waterway', 'stream'), 'deprecated', 'use type=waterway, waterway=stream'],
 [ ('destination_sign',), 'established', ''],
 [ ('dual_carriageway',), 'proposed', ''],
 [ ('enforcement',), 'incomplete', 'should have an extra enforcement= tag'],
 [ ('enforcement','max_speed'), 'typo', 'use enforcement=maxspeed tag'],
 [ ('enforcement','maxspeed'), 'incomplete', 'should have an extra maxspeed= tag'],
 [ ('enforcement','maxspeed','100'), 'established', ''],
 [ ('enforcement','maxspeed','110'), 'established', ''],
 [ ('enforcement','maxspeed','120'), 'established', ''],
 [ ('enforcement','maxspeed','130'), 'established', ''],
 [ ('enforcement','maxspeed','30'), 'established', ''],
 [ ('enforcement','maxspeed','30 mph'), 'established', ''],
 [ ('enforcement','maxspeed','40'), 'established', ''],
 [ ('enforcement','maxspeed','40 mph'), 'established', ''],
 [ ('enforcement','maxspeed','50'), 'established', ''],
 [ ('enforcement','maxspeed','60'), 'established', ''],
 [ ('enforcement','maxspeed','60 mph'), 'established', ''],
 [ ('enforcement','maxspeed','70'), 'established', ''],
 [ ('enforcement','maxspeed','80'), 'established', ''],
 [ ('enforcement','maxspeed','90'), 'established', ''],
 [ ('enforcement','speed'), 'typo', 'use enforcement=maxspeed tag'],
 [ ('label',), 'proposed', ''],
 [ ('multipolygon',), 'established', ''],
 [ ('network',), 'proposed', ''],
 [ ('public_transport','stop_area'), 'established', ''],
 [ ('public_transport','stop_area_group'), 'established', ''],
 [ ('region',), 'proposed', ''],
 [ ('relation',), 'strange', 'check required'],
 [ ('relatedStreet',), 'proposed', 'use associatedStreet if possible'],
 [ ('restriction',), 'incomplete', 'shoud have an extra restriction= tag'],
 [ ('restriction','no_right_turn'), 'established', ''],
 [ ('restriction','only_right_turn'), 'established', ''],
 [ ('restriction','no_left_turn'), 'established', ''],
 [ ('restriction','only_left_turn'), 'established', ''],
 [ ('restriction','no_u_turn'), 'established', ''],
 [ ('restriction','no_straight_on'), 'established', ''],
 [ ('restriction','only_straight_on'), 'established', ''],
 [ ('river',), 'deprecated', 'use type=waterway, waterway=river'],
 [ ('route',), 'incomplete', 'type=route should have an additional route= tag'],
 [ ('route','bicycle'), 'established', ''],
 [ ('route','bicycle','lcn'), 'misplaced_value', 'use network=lcn'],
 [ ('route','bicycle','rcn'), 'misplaced_value', 'use network=rcn'],
 [ ('route','bicycle','yes'), 'redundant', 'bicycle=yes not required'],
 [ ('route','bus'), 'established', ''],
 [ ('route','bus','yes'), 'redundant', 'bus=yes not required'],
 [ ('route','bus','trolleybus'), 'misplaced_value', 'use route=trolleybus'],
 [ ('route','bycicle'), 'typo', 'use route=bicycle'],
 [ ('route','detour'), 'established', ''],
 [ ('route','ferry'), 'established', ''],
 [ ('route','fitness_trail'), 'proposed', ''],
 [ ('route','foot'), 'established', ''],
 [ ('route','foot','lwn'), 'misplaced_value', 'lwn is a network tag'],
 [ ('route','foot','lwn', 'yes'), 'misplaced_value', 'lwn is a network tag'],
 [ ('route','foot','nwn'), 'misplaced_value', 'nwn is a network tag'],
 [ ('route','foot','rwn'), 'misplaced_value', 'rwn is a network tag'],
 [ ('route','foot','yes'), 'redundant', 'foot=yes not required'],
 [ ('route','hiking'), 'established', ''],
 [ ('route','hiking','lwn'), 'misplaced_value', 'lwn is a network tag'],
 [ ('route','hiking','lwn', 'yes'), 'misplaced_value', 'lwn is a network tag'],
 [ ('route','hiking','nwn'), 'misplaced_value', 'nwn is a network tag'],
 [ ('route','hiking','rwn'), 'misplaced_value', 'rwn is a network tag'],
 [ ('route','horse'), 'established', ''],
 [ ('route','horse','yes'), 'redundant', 'horse=yes not required'],
 [ ('route','light_rail'), 'established', ''],
 [ ('route','mtb'), 'established', ''],
 [ ('route','piste'), 'established', ''],
 [ ('route','power'), 'established', ''],
 [ ('route','railway'), 'established', ''],
 [ ('route','road'), 'established', ''],
 [ ('route','river'), 'deprecated', 'use type=waterway, waterway=river'],
 [ ('route','ski'), 'established', ''],
 [ ('route','ski','yes'), 'redundant', 'ski=yes not required'],
 [ ('route','stream'), 'deprecated', 'use type=waterway, waterway=stream'],
 [ ('route','subway'), 'established', ''],
 [ ('route','train'), 'established', ''],
 [ ('route','tram'), 'established', ''],
 [ ('route','trolleybus'), 'established', ''],
 [ ('route','pilgrimage'), 'deprecated', 'use route=hiking or route=bicycle and pilgrimage=yes'],
 [ ('route','waterway'), 'deprecated', 'use type=waterway, waterway=*'],
 [ ('site',), 'proposed', ''],
 [ ('street',), 'proposed', ''],
 [ ('tunnel',), 'proposed', ''],
 [ ('tunnel','yes'), 'redundant', 'tunnel=yes not required'],
 [ ('waterway',), 'incomplete', 'should have an extra waterway tag'],
 [ ('waterway','canal'), 'established', ''],
 [ ('waterway','drain'), 'established', ''],
 [ ('waterway','ditch'), 'established', ''],
 [ ('waterway','river'), 'established', ''],
 [ ('waterway','stream'), 'established', ''],
]

TYPE_COLLECTIONS = [[ ('route', 'detour', 'A [1-9][0-9]*$'), 'established', 'regex collection'],
                    [ ('postal_code', '[0-9][ 0-9]*$'), '', 'regex collection'],
                    [ ('addr:postcode', '[0-9][0-9]*$'), '', 'regex collection'],
                    [ ('boundary', 'postal_code', '[0-9][0-9]*$'), '', 'regex collection'],
                    [ ('network', '.*Kreisstra.*'), 'misplaced_value', 'regex collection: should be tagged as road network']
                    ]
 
STATUS_COLORS = [('established', '#00FF00'),
                 ('proposed', '#88FF88'),
                 ('incomplete', '#FFFF66'),
                 ('misplaced_value', '#AAAAFF'),
                 ('redundant', '#8888FF'),
                 ('typo', '#FF7777'),
                 ('strange', '#FF4444'),
                 ('deprecated', '#CCCCCC')
                 ]

RELATION_ROLES = {'multipolygon': dict([('','wr'),('outer','wr'),('inner','wr'),
                                        ('admin_centre','n'),('subarea','r'),('label','n')]),
                  'waterway':dict([('','w'),('main_stream','w'),('side_stream','w'),
                                   ('tributary','r'),('spring','n')]),
                  'collection':dict([('','rwn')]),
                  }
                                      
